services:
  postgres:
    image: postgres:17
    container_name: dating_postgres
    restart: unless-stopped

    environment:
      POSTGRES_USER: dating_user
      POSTGRES_PASSWORD: dating_password
      POSTGRES_DB: dating_db

    ports:
      - "5432:5432"

    volumes:
      - dating_postgres_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: dating_redis
    restart: unless-stopped

    ports:
      - "6379:6379"

volumes:
  dating_postgres_data: