import { datingProfileConfig } from '../../config/datingProfile';
import {
  InterestCategoryService,
  InterestService,
  LanguageService,
  OnboardingStepService,
  PersonalityFrameworkService,
  PersonalityTypeService,
  ProfileOptionCategoryService,
  ProfileOptionService,
  PromptCategoryService,
  PromptService,
  ValueService,
} from './catalog.services';

export class DatingCatalogService {
  constructor(
    private readonly profileOptionCategoryService = new ProfileOptionCategoryService(),
    private readonly profileOptionService = new ProfileOptionService(),
    private readonly interestCategoryService = new InterestCategoryService(),
    private readonly interestService = new InterestService(),
    private readonly languageService = new LanguageService(),
    private readonly promptCategoryService = new PromptCategoryService(),
    private readonly promptService = new PromptService(),
    private readonly valueService = new ValueService(),
    private readonly personalityFrameworkService = new PersonalityFrameworkService(),
    private readonly personalityTypeService = new PersonalityTypeService(),
    private readonly onboardingStepService = new OnboardingStepService(),
  ) {}

  async get(version = 1) {
    const [
      profileOptionCategories,
      profileOptions,
      interestCategories,
      interests,
      languages,
      promptCategories,
      prompts,
      values,
      personalityFrameworks,
      personalityTypes,
      onboardingSteps,
    ] = await Promise.all([
      this.profileOptionCategoryService.listActive(),
      this.profileOptionService.listActive(),
      this.interestCategoryService.listActive(),
      this.interestService.listActive(),
      this.languageService.listActive(),
      this.promptCategoryService.listActive(),
      this.promptService.listActive(),
      this.valueService.listActive(),
      this.personalityFrameworkService.listActive(),
      this.personalityTypeService.listActive(),
      this.onboardingStepService.listActive(version),
    ]);

    return {
      onboardingVersion: version,
      rules: {
        minimumAge: datingProfileConfig.minimumAge,
        minimumPhotos: datingProfileConfig.minimumPhotos,
        maximumPhotos: datingProfileConfig.maximumPhotos,
        minimumInterests: datingProfileConfig.minimumInterests,
        maximumInterests: datingProfileConfig.maximumInterests,
        maximumPromptAnswers: datingProfileConfig.maximumPromptAnswers,
      },
      consent: {
        policyVersion: datingProfileConfig.consentPolicyVersion,
        requiredCodes: [...datingProfileConfig.requiredConsentCodes],
        optionalCodes: [
          'SENSITIVE_PROFILE_DATA',
          'PERSONALIZED_MATCHING',
          'PERSONALITY_MATCHING',
        ],
      },
      profileOptionCategories: profileOptionCategories.map((category) => ({
        id: category.id,
        code: category.code,
        name: category.name,
        labelKey: category.labelKey,
        selectionMode: category.selectionMode,
        minSelections: category.minSelections,
        maxSelections: category.maxSelections,
        isSensitive: category.isSensitive,
        allowProfileVisibility: category.allowProfileVisibility,
        allowMatchPreference: category.allowMatchPreference,
        allowDealbreaker: category.allowDealbreaker,
        isRequiredForOnboarding: category.isRequiredForOnboarding,
        displayOrder: category.displayOrder,
      })),
      profileOptions: profileOptions.map((option) => ({
        id: option.id,
        categoryId: option.categoryId,
        code: option.code,
        label: option.label,
        labelKey: option.labelKey,
        description: option.description,
        displayOrder: option.displayOrder,
      })),
      interestCategories: interestCategories.map((category) => ({
        id: category.id,
        code: category.code,
        name: category.name,
        labelKey: category.labelKey,
        displayOrder: category.displayOrder,
      })),
      interests: interests.map((interest) => ({
        id: interest.id,
        categoryId: interest.categoryId,
        code: interest.code,
        name: interest.name,
        labelKey: interest.labelKey,
        description: interest.description,
        displayOrder: interest.displayOrder,
      })),
      languages: languages.map((language) => ({
        id: language.id,
        isoCode: language.isoCode,
        name: language.name,
        nativeName: language.nativeName,
      })),
      promptCategories: promptCategories.map((category) => ({
        id: category.id,
        code: category.code,
        name: category.name,
        labelKey: category.labelKey,
        displayOrder: category.displayOrder,
      })),
      prompts: prompts.map((prompt) => ({
        id: prompt.id,
        categoryId: prompt.categoryId,
        code: prompt.code,
        promptText: prompt.promptText,
        labelKey: prompt.labelKey,
        responseType: prompt.responseType,
        maxAnswerLength: prompt.maxAnswerLength,
        displayOrder: prompt.displayOrder,
      })),
      values: values.map((value) => ({
        id: value.id,
        code: value.code,
        name: value.name,
        labelKey: value.labelKey,
        description: value.description,
        displayOrder: value.displayOrder,
      })),
      personalityFrameworks: personalityFrameworks.map((framework) => ({
        id: framework.id,
        code: framework.code,
        name: framework.name,
        description: framework.description,
        resultMode: framework.resultMode,
      })),
      personalityTypes: personalityTypes.map((type) => ({
        id: type.id,
        frameworkId: type.frameworkId,
        code: type.code,
        name: type.name,
        description: type.description,
      })),
      onboardingSteps: onboardingSteps.map((step) => ({
        id: step.id,
        onboardingVersion: step.onboardingVersion,
        code: step.code,
        name: step.name,
        sequence: step.sequence,
        isRequired: step.isRequired,
        isSkippable: step.isSkippable,
      })),
    };
  }
}
